spring:
  data:
    mongodb:
      url: mongodb://localhost:27017/orderdb
      host: localhost
      port: 27017
      database: orderdb
      repositories:
        enable: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/